# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deepvariant/protos/resources.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'deepvariant/protos/resources.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"deepvariant/protos/resources.proto\x12\x1dlearning.genomics.deepvariant\"\x95\x02\n\x0fResourceMetrics\x12\x11\n\thost_name\x18\x01 \x01(\t\x12\x1b\n\x13physical_core_count\x18\x02 \x01(\x05\x12\x19\n\x11\x63pu_frequency_mhz\x18\x03 \x01(\x01\x12\x17\n\x0ftotal_memory_mb\x18\x04 \x01(\x05\x12\x19\n\x11wall_time_seconds\x18\x05 \x01(\x01\x12\x1d\n\x15\x63pu_user_time_seconds\x18\x06 \x01(\x01\x12\x1f\n\x17\x63pu_system_time_seconds\x18\x07 \x01(\x01\x12\x1a\n\x12memory_peak_rss_mb\x18\x08 \x01(\x05\x12\x12\n\nread_bytes\x18\t \x01(\x03\x12\x13\n\x0bwrite_bytes\x18\n \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deepvariant.protos.resources_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCEMETRICS']._serialized_start=70
  _globals['_RESOURCEMETRICS']._serialized_end=347
# @@protoc_insertion_point(module_scope)
